routes/web.php
Route::get('choice_classe/{id}',[App\Http\Controllers\EnseignantController::class,'getNiveaEleveAdd']);
Route::post('/update/student/class/{id}',[App\Http\Controllers\EnseignantController::class,'updateClasseStudent']);
Route::resource('anneeScolaires', App\Http\Controllers\AnneeScolaireController::class);
Route::get('get_enseignant_on_class', [App\Http\Controllers\EnseignantController::class,'getClasseByTeacher'])->name('get_enseignant_class.eleve');
Route::get('get_enseignantafter_class/{id}', [App\Http\Controllers\EnseignantController::class,'getEnseignantByTypeEnseignement']);
Route::get('get_classe_enseignantafter_class/{id}', [App\Http\Controllers\EnseignantController::class,'getEnseignantByClasseEnseign']);
Route::get('get_classe_eneseignant_eleve/{id}', [App\Http\Controllers\EnseignantController::class,'getEleveByClasseAndEnseignant']);
Route::get('carte_student/{slug}',[App\Http\Controllers\EleveController::class,'getStudentCard'])->name('carte.eleve');
Route::get('carte_all_years/{id}',[App\Http\Controllers\EleveController::class,'getCarteStudentPrinting'])->name('carte.year');

Route::get('get_eleve_to_paiement/{slug}',[App\Http\Controllers\EleveController::class,'getEleveToAddInscription']);
Route::get('get_eleve_on_paiment_by_year',[App\Http\Controllers\EleveController::class,'getPaiementEleveByYear'])->name('paiment.eleve');
Route::post('eleve/new_classes',[App\Http\Controllers\EleveController::class,'getEleveWithNumero'])->name('elevegetting.classe');
Route::post('add_eleve_classe_continuons/{id}',[App\Http\Controllers\EleveController::class,'AddClasseEleveContinuons']);
Route::post('add_eleveclass_with_prof_arab/{id}',[App\Http\Controllers\EleveController::class,'AddClasseEleveContinuonsArabe']);
Route::get('eleve/inscription_new',[App\Http\Controllers\EleveController::class,'getFormtoInscrire'])->name('eleve.new_inscription');
Route::get('eleve/reinscription_new',[App\Http\Controllers\EleveController::class,'getFormtoReInscrire'])->name('eleve.new_reinscription');
Route::resource('inscriptionEleves', App\Http\Controllers\InscriptionEleveController::class);
Route::resource('inscriptionEleves', App\Http\Controllers\InscriptionEleveController::class);
Route::resource('regimes', App\Http\Controllers\RegimeController::class);
Route::resource('fraisInscriptions', App\Http\Controllers\FraisInscriptionController::class);
Route::resource('paiementEleves', App\Http\Controllers\PaiementEleveController::class);
Route::get('get_elevt_to_paie_by_momth/{id}',[App\Http\Controllers\EleveController::class,'getEleveToAddPaiement']);
Route::post('get_elev_paiement',[App\Http\Controllers\EleveController::class,'SearchingElevePaiement'])->name('get_eleve_to_paiement.annee_scolaire');
Route::get('recu/paiement/{slug}',[App\Http\Controllers\PaiementEleveController::class,'getPrinRecu'])->name('get_recu.annee_scolaire');
Route::get('recu/paiement_mensual/{slug}',[App\Http\Controllers\PaiementEleveController::class,'getPaiementMonthRecu'])->name('get_recu_mensual.annee_scolaire');
Route::post('change_status_confime/{id}',[App\Http\Controllers\EleveController::class,'ChangeStatusPaiement']);
Route::resource('enseignantAnnees', App\Http\Controllers\EnseignantAnneeController::class);
Route::post('paiement_mensual/{id}',[App\Http\Controllers\EleveController::class,'PaiementMonthPosted'])->name('paiement.mensual');
Route::resource('mensualiteEleves', App\Http\Controllers\MensualiteEleveController::class);
Route::get('infos_after_paiement/{slug}',[App\Http\Controllers\EleveController::class,'getInfoPaiementMonth'])->name('infor_paiement.mensual');
Route::post('eleve/getting_years',[App\Http\Controllers\EleveController::class,'getEleveNumeroPost'])->name('getting_eleves.classe');
Route::get('/depense_by_category/{slug}',[App\Http\Controllers\DepenseCategorieController::class,'getDeCategory'])->name('depense.category_depense');
Route::get('paiment_enseignant/{slug}',[App\Http\Controllers\MensuualiteEnseignantController::class,'getInfoPaiementEnseignant'])->name('enseignant.paiement');
Route::get('recu_paiment_enseignant/{slug}',[App\Http\Controllers\MensuualiteEnseignantController::class,'getRecuPaiement'])->name('enseignant.recu_paiement');
Route::resource('depenseCategories', App\Http\Controllers\DepenseCategorieController::class);
Route::get('edit_profil/{slug}',[App\Http\Controllers\UserController::class,'ChangeInfoProfile'])->name('edit.profil');
Route::post('edit_profil_user',[App\Http\Controllers\UserController::class,'UpdateProfileAdmin'])->name('edit.profil_user');
Route::post('edit_password_user',[App\Http\Controllers\UserController::class,'ChangePassword'])->name('password.profil_user');
Route::post('changing_password_user/{id}',[App\Http\Controllers\UserController::class,'ChangePasswordUser'])->name('password.changing');
Route::get('get-list-paiement-status',[App\Http\Controllers\PaiementEleveController::class,'getListePaiementStudent'])->name('get_list_status.annuelle');
Route::post('get_list_par_moi',[App\Http\Controllers\PaiementEleveController::class,'getStudentPaiementDayByyear'])->name('get_list_par_moi.annuelle');
Route::get('get-list-depenses-status',[App\Http\Controllers\PaiementEleveController::class,'getListeDepensesStatus'])->name('get_list_status_depenses.annuelle');
Route::post('get_list_depenses_moi',[App\Http\Controllers\PaiementEleveController::class,'getlistofdepensebydate'])->name('get_list_depense_moi.annuelle');
// Route::get('tasks',[App\Http\Controllers\PaiementEleveController::class,'exportCsv']);

Route::resource('mensuualiteEnseignants', App\Http\Controllers\MensuualiteEnseignantController::class);
Route::resource('evaluationSemestres', App\Http\Controllers\EvaluationSemestreController::class);
Route::get('index_eleves',[App\Http\Controllers\EvaluationSemestreController::class,'indexinfo'])->name('getinfos.eleve');
Route::get('get_eleve_evaluation/{slug}',[App\Http\Controllers\EvaluationSemestreController::class,'GetEvaluationEleve'])->name('evaluation_detail.eleve');
Route::get('get_evaluation/{id}',[App\Http\Controllers\EvaluationSemestreController::class,'getEleveToEvaluated'])->name('evaluation.eleve');

Route::resource('evaluationMensuels', App\Http\Controllers\EvaluationMensuelController::class);
Route::get('get_mensuel_evalution/{slug}',[App\Http\Controllers\EvaluationSemestreController::class,'getEleveToEvaluatedMensuel'])->name('evaluation_mensuel_detail.eleve');
Route::get('get_evaluer_mont/{id}',[App\Http\Controllers\EvaluationSemestreController::class,'getEleveToEvaluerModalMensuel']);
Route::get('create/parent',[App\Http\Controllers\UserController::class,'GetTocreateParent'])->name('create_eleve.parent');
Route::post('parent/user',[App\Http\Controllers\UserController::class,'CreateParent'])->name('create_parent.post');
Route::patch('parent/user/{id}',[App\Http\Controllers\UserController::class,'updateParent'])->name('create_parent.update');
Route::resource('sourates', App\Http\Controllers\SourateController::class);
Route::get('dashboard/parent',[App\Http\Controllers\UserController::class,'dashboardParent'])->name('dashboard.parent');
Route::get('get_Eleve_by_parent',[App\Http\Controllers\ParentsController::class,'GetParentEleve'])->name('eleve_parent.parent');
Route::get('get_Eleve_by_parent/{slug}',[App\Http\Controllers\ParentsController::class,'GetInfoEleveByParent'])->name('eleve_parent_slug.parent');
Route::get('get_Eleve_by_parent_evalutation_mensuel',[App\Http\Controllers\ParentsController::class,'GetParentEleveMensuel'])->name('eleve_parent_evaaluation_mensuel.parent');
Route::get('get_Eleve_by_parent_evalutation_hebdomadaire',[App\Http\Controllers\ParentsController::class,'GetParentEleveHebdomadaire'])->name('eleve_parent_evaaluation_hebdomadaire.parent');
Route::get('get_Eleve_by_parent_paiement',[App\Http\Controllers\ParentsController::class,'GetParentElevePaiement'])->name('eleve_parent_paiement.parent');


Route::get('suivie_evalution_Eleve_by_parent/{slug}',[App\Http\Controllers\ParentsController::class,'GetEValuationSemestreByParent'])->name('suivie_evaluation.parent');
Route::get('suivie_evalution_mensuel_Eleve_by_parent/{slug}',[App\Http\Controllers\ParentsController::class,'GetEvaluationMensuelEleveByParent'])->name('suivie_evaluation_mensuel.parent');


Route::resource('parents', App\Http\Controllers\ParentsController::class);

Route::get('eleve/paiement/all',[App\Http\Controllers\EleveController::class,'getEleveAllByPaiement'])->name('eleve.get_all_paiement');
Route::get('eleve/paiement/{query}/',[App\Http\Controllers\EleveController::class,'getListOfEleveNonPaiement'])->name('eleve.get_paiement_non_paied');

Route::resource('messageContacts', App\Http\Controllers\MessageContactController::class);


Route::resource('aproposCarfeis', App\Http\Controllers\AproposCarfeisController::class);

//Route pour Paydunya

Route::get('paydunya-payment-form/{slug}',[App\Http\Controllers\PaydunyaCarfeisController::class,'getPaydunyaPaymentView'])->name('paydunya.payment.form');
Route::post('larapaydunya-sending-payment-infos',[App\Http\Controllers\PaydunyaCarfeisController::class,'postPayDunyaPaymentInfos'])->name('sending.payment.infos');
Route::post('payment-form',[App\Http\Controllers\PaydunyaCarfeisController::class,'getPaydunyaPaymentView'])->name('payment.form');
Route::post('payment-process',[App\Http\Controllers\PaydunyaCarfeisController::class,'postPaydunyaPaymentProcess'])->name('paydunya.payment.process');
Route::get('return/paydunya-payment-status',[App\Http\Controllers\PaydunyaCarfeisController::class,'paydunyaPaymentStatus'])->name('paydunya.payment.status');

Route::post('paiement_mensual_paydunya/{id}',[App\Http\Controllers\EleveController::class,'PaiementMonthPostedPaydunua'])->name('paiement.mensual_paydunya');

Route::get('infos_after_paiement_parent/{slug}',[App\Http\Controllers\ParentsController::class,'getInfoPaiementMonthByparent'])->name('infor_paiement_parent.mensual');

app/Models/MensualiteEleve.php
<?php

namespace App\Models;

use Eloquent as Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Cviebrock\EloquentSluggable\Sluggable;

/**
 * Class MensualiteEleve
 * @package App\Models
 * @version October 10, 2021, 10:12 am UTC
 *
 * @property string $paiement_eleve_id
 * @property string $eleve_id
 * @property string $annee_scolaire_id
 * @property string $month
 * @property string $mensualite
 * @property string $observation
 */
class MensualiteEleve extends Model
{
    use SoftDeletes;
    use Sluggable;

    use HasFactory;

    public $table = 'mensualite_eleves';
    

    protected $dates = ['deleted_at'];



    public $fillable = [
        'paiement_eleve_id',
        'eleve_id',
        'annee_scolaire_id',
        'month',
        'mensualite',
        'observation',
        'montant_attendu',
        'number_month',
        'slug',
        'user_id',
        'periode_end',
        'periode_debut',
        'numero'
    ];

    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [
        'paiement_eleve_id' => 'string',
        'eleve_id' => 'string',
        'annee_scolaire_id' => 'string',
        'month' => 'string',
        'mensualite' => 'string',
        'observation' => 'string'
    ];

    /**
     * Validation rules
     *
     * @var array
     */
    public static $rules = [
        'paiement_eleve_id' => 'required',
        'eleve_id' => 'required',
        'annee_scolaire_id' => 'required',
        'month' => 'required',
        'mensualite' => 'required',
        'user_id' => 'required'
    ];

        /**
     * Return the sluggable configuration array for this model.
     *
     * @return array
     */
    public function sluggable(): array
    {
        return [
            'slug' => [
                'source' => ['month','mensualite','montant_attendu'],
            ]
        ];
    } 

      /**
     * Get the candidat that owns the eleve
     *
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function user()
    {
        return $this->belongsTo(User::class, 'user_id');
    }
     /**
     * Get the candidat that owns the eleve
     *
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function eleve()
    {
        return $this->belongsTo(Eleve::class, 'eleve_id');
    }

     /**
     * Get the candidat that owns the eleve
     *
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function annee_scolaire()
    {
        return $this->belongsTo(AnneeScolaire::class, 'annee_scolaire_id');
    }
     /**
     * Get the candidat that owns the eleve
     *
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function paiement()
    {
        return $this->belongsTo(PaiementEleve::class, 'paiement_eleve_id');
    }
}

app/Http/Controllers/MensualiteEleveController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\CreateMensualiteEleveRequest;
use App\Http\Requests\UpdateMensualiteEleveRequest;
use App\Repositories\MensualiteEleveRepository;
use App\Http\Controllers\AppBaseController;
use Illuminate\Http\Request;
use Flash;
use Response;

class MensualiteEleveController extends AppBaseController
{
    /** @var  MensualiteEleveRepository */
    private $mensualiteEleveRepository;

    public function __construct(MensualiteEleveRepository $mensualiteEleveRepo)
    {
        $this->mensualiteEleveRepository = $mensualiteEleveRepo;
    }

    /**
     * Display a listing of the MensualiteEleve.
     *
     * @param Request $request
     *
     * @return Response
     */
    public function index(Request $request)
    {
        $mensualiteEleves = $this->mensualiteEleveRepository->all();

        return view('mensualite_eleves.index')
            ->with('mensualiteEleves', $mensualiteEleves);
    }

    /**
     * Show the form for creating a new MensualiteEleve.
     *
     * @return Response
     */
    public function create()
    {
        return view('mensualite_eleves.create');
    }

    /**
     * Store a newly created MensualiteEleve in storage.
     *
     * @param CreateMensualiteEleveRequest $request
     *
     * @return Response
     */
    public function store(CreateMensualiteEleveRequest $request)
    {
        $input = $request->all();

        $mensualiteEleve = $this->mensualiteEleveRepository->create($input);

        Flash::success('Mensualite Eleve ajouté(e) avec success');

        return redirect(route('mensualiteEleves.index'));
    }

    /**
     * Display the specified MensualiteEleve.
     *
     * @param int $id
     *
     * @return Response
     */
    public function show($id)
    {
        $mensualiteEleve = $this->mensualiteEleveRepository->find($id);

        if (empty($mensualiteEleve)) {
            Flash::error('Mensualite Eleve  non trouvé(e)');

            return redirect(route('mensualiteEleves.index'));
        }

        return view('mensualite_eleves.show')->with('mensualiteEleve', $mensualiteEleve);
    }

    /**
     * Show the form for editing the specified MensualiteEleve.
     *
     * @param int $id
     *
     * @return Response
     */
    public function edit($id)
    {
        $mensualiteEleve = $this->mensualiteEleveRepository->find($id);

        if (empty($mensualiteEleve)) {
            Flash::error('Mensualite Eleve  non trouvé(e)');

            return redirect(route('mensualiteEleves.index'));
        }

        return view('mensualite_eleves.edit')->with('mensualiteEleve', $mensualiteEleve);
    }

    /**
     * Update the specified MensualiteEleve in storage.
     *
     * @param int $id
     * @param UpdateMensualiteEleveRequest $request
     *
     * @return Response
     */
    public function update($id, UpdateMensualiteEleveRequest $request)
    {
        $mensualiteEleve = $this->mensualiteEleveRepository->find($id);

        if (empty($mensualiteEleve)) {
            Flash::error('Mensualite Eleve  non trouvé(e)');

            return redirect(route('mensualiteEleves.index'));
        }

        $mensualiteEleve = $this->mensualiteEleveRepository->update($request->all(), $id);

        Flash::success('Mensualite Eleve modifié(e) avec success.');

        return redirect(route('mensualiteEleves.index'));
    }

    /**
     * Remove the specified MensualiteEleve from storage.
     *
     * @param int $id
     *
     * @throws \Exception
     *
     * @return Response
     */
    public function destroy($id)
    {
        $mensualiteEleve = $this->mensualiteEleveRepository->find($id);

        if (empty($mensualiteEleve)) {
            Flash::error('Mensualite Eleve  non trouvé(e)');

            return redirect(route('mensualiteEleves.index'));
        }

        $this->mensualiteEleveRepository->delete($id);
        Flash::success('Mensualite Eleve deleted successfully.');
        return redirect(route('get_eleve_to_paiement.annee_scolaire'));
        // return redirect(route('mensualiteEleves.index'));
    }
}

resources/views/mensualite_eleves/create.blade.php
@extends('layouts.app')

@section('content')
    <ol class="breadcrumb">
      <li class="breadcrumb-item">
         <a href="{!! route('mensualiteEleves.index') !!}">Mensualite Eleve</a>
      </li>
      <li class="breadcrumb-item active">Create</li>
    </ol>
     <div class="container-fluid">
          <div class="animated fadeIn">
                @include('coreui-templates::common.errors')
                <div class="row">
                    <div class="col-lg-12">
                        <div class="card">
                            <div class="card-header">
                                <i class="fa fa-plus-square-o fa-lg"></i>
                                <strong>Create Mensualite Eleve</strong>
                            </div>
                            <div class="card-body">
                                {!! Form::open(['route' => 'mensualiteEleves.store']) !!}

                                   @include('mensualite_eleves.fields')

                                {!! Form::close() !!}
                            </div>
                        </div>
                    </div>
                </div>
           </div>
    </div>
@endsection

resources/views/mensualite_eleves/edit.blade.php
@extends('layouts.app')

@section('content')
    <ol class="breadcrumb">
          <li class="breadcrumb-item">
             <a href="{!! route('mensualiteEleves.index') !!}">Mensualite Eleve</a>
          </li>
          <li class="breadcrumb-item active">Edit</li>
        </ol>
    <div class="container-fluid">
         <div class="animated fadeIn">
             @include('coreui-templates::common.errors')
             <div class="row">
                 <div class="col-lg-12">
                      <div class="card">
                          <div class="card-header">
                              <i class="fa fa-edit fa-lg"></i>
                              <strong>Edit Mensualite Eleve</strong>
                          </div>
                          <div class="card-body">
                              {!! Form::model($mensualiteEleve, ['route' => ['mensualiteEleves.update', $mensualiteEleve->id], 'method' => 'patch']) !!}

                              @include('mensualite_eleves.fields')

                              {!! Form::close() !!}
                            </div>
                        </div>
                    </div>
                </div>
         </div>
    </div>
@endsection

resources/views/mensualite_eleves/fields.blade.php
<!-- Paiement Eleve Id Field -->
<div class="form-group col-sm-6">
    {!! Form::label('paiement_eleve_id', 'Paiement Eleve Id:') !!}
    {!! Form::text('paiement_eleve_id', null, ['class' => 'form-control']) !!}
</div>

<!-- Eleve Id Field -->
<div class="form-group col-sm-6">
    {!! Form::label('eleve_id', 'Eleve Id:') !!}
    {!! Form::text('eleve_id', null, ['class' => 'form-control']) !!}
</div>

<!-- Annee Scolaire Id Field -->
<div class="form-group col-sm-6">
    {!! Form::label('annee_scolaire_id', 'Annee Scolaire Id:') !!}
    {!! Form::text('annee_scolaire_id', null, ['class' => 'form-control']) !!}
</div>

<!-- Month Field -->
<div class="form-group col-sm-6">
    {!! Form::label('month', 'Month:') !!}
    {!! Form::text('month', null, ['class' => 'form-control']) !!}
</div>

<!-- Mensualite Field -->
<div class="form-group col-sm-6">
    {!! Form::label('mensualite', 'Mensualite:') !!}
    {!! Form::text('mensualite', null, ['class' => 'form-control']) !!}
</div>

<!-- Observation Field -->
<div class="form-group col-sm-6">
    {!! Form::label('observation', 'Observation:') !!}
    {!! Form::text('observation', null, ['class' => 'form-control']) !!}
</div>

<!-- Submit Field -->
<div class="form-group col-sm-12">
    {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
    <a href="{{ route('mensualiteEleves.index') }}" class="btn btn-secondary">Cancel</a>
</div>

resources/views/mensualite_eleves/index.blade.php
@extends('layouts.app')

@section('content')
    <ol class="breadcrumb">
        <li class="breadcrumb-item">Mensualite Eleves</li>
    </ol>
    <div class="container-fluid">
        <div class="animated fadeIn">
             @include('flash::message')
             <div class="row">
                 <div class="col-lg-12">
                     <div class="card">
                         <div class="card-header">
                             <i class="fa fa-align-justify"></i>
                             MensualiteEleves
                             <a class="pull-right" href="{{ route('mensualiteEleves.create') }}"><i class="fa fa-plus-square fa-lg"></i></a>
                         </div>
                         <div class="card-body">
                             @include('mensualite_eleves.table')
                              <div class="pull-right mr-3">
                                     
                              </div>
                         </div>
                     </div>
                  </div>
             </div>
         </div>
    </div>
@endsection

resources/views/mensualite_eleves/show.blade.php
@extends('layouts.app')

@section('content')
     <ol class="breadcrumb">
            <li class="breadcrumb-item">
                <a href="{{ route('mensualiteEleves.index') }}">Mensualite Eleve</a>
            </li>
            <li class="breadcrumb-item active">Detail</li>
     </ol>
     <div class="container-fluid">
          <div class="animated fadeIn">
                 @include('coreui-templates::common.errors')
                 <div class="row">
                     <div class="col-lg-12">
                         <div class="card">
                             <div class="card-header">
                                 <strong>Details</strong>
                                  <a href="{{ route('mensualiteEleves.index') }}" class="btn btn-light">Back</a>
                             </div>
                             <div class="card-body">
                                 @include('mensualite_eleves.show_fields')
                             </div>
                         </div>
                     </div>
                 </div>
          </div>
    </div>
@endsection

resources/views/mensualite_eleves/show_fields.blade.php
<!-- Paiement Eleve Id Field -->
<div class="form-group">
    {!! Form::label('paiement_eleve_id', 'Paiement Eleve Id:') !!}
    <p>{{ $mensualiteEleve->paiement_eleve_id }}</p>
</div>

<!-- Eleve Id Field -->
<div class="form-group">
    {!! Form::label('eleve_id', 'Eleve Id:') !!}
    <p>{{ $mensualiteEleve->eleve_id }}</p>
</div>

<!-- Annee Scolaire Id Field -->
<div class="form-group">
    {!! Form::label('annee_scolaire_id', 'Annee Scolaire Id:') !!}
    <p>{{ $mensualiteEleve->annee_scolaire_id }}</p>
</div>

<!-- Month Field -->
<div class="form-group">
    {!! Form::label('month', 'Month:') !!}
    <p>{{ $mensualiteEleve->month }}</p>
</div>

<!-- Mensualite Field -->
<div class="form-group">
    {!! Form::label('mensualite', 'Mensualite:') !!}
    <p>{{ $mensualiteEleve->mensualite }}</p>
</div>

<!-- Observation Field -->
<div class="form-group">
    {!! Form::label('observation', 'Observation:') !!}
    <p>{{ $mensualiteEleve->observation }}</p>
</div>

<!-- Created At Field -->
<div class="form-group">
    {!! Form::label('created_at', 'Created At:') !!}
    <p>{{ $mensualiteEleve->created_at }}</p>
</div>

<!-- Updated At Field -->
<div class="form-group">
    {!! Form::label('updated_at', 'Updated At:') !!}
    <p>{{ $mensualiteEleve->updated_at }}</p>
</div>

resources/views/mensualite_eleves/table.blade.php
<div class="table-responsive-sm">
    <table class="table table-striped" id="mensualiteEleves-table">
        <thead>
            <tr>
                <th>Paiement Eleve Id</th>
        <th>Eleve Id</th>
        <th>Annee Scolaire Id</th>
        <th>Month</th>
        <th>Mensualite</th>
        <th>Observation</th>
                <th colspan="3">Action</th>
            </tr>
        </thead>
        <tbody>
        @foreach($mensualiteEleves as $mensualiteEleve)
            <tr>
                <td>{{ $mensualiteEleve->paiement_eleve_id }}</td>
            <td>{{ $mensualiteEleve->eleve_id }}</td>
            <td>{{ $mensualiteEleve->annee_scolaire_id }}</td>
            <td>{{ $mensualiteEleve->month }}</td>
            <td>{{ $mensualiteEleve->mensualite }}</td>
            <td>{{ $mensualiteEleve->observation }}</td>
                <td>
                    {!! Form::open(['route' => ['mensualiteEleves.destroy', $mensualiteEleve->id], 'method' => 'delete']) !!}
                    <div class='btn-group'>
                        <a href="{{ route('mensualiteEleves.show', [$mensualiteEleve->id]) }}" class='btn btn-ghost-success'><i class="fa fa-eye"></i></a>
                        <a href="{{ route('mensualiteEleves.edit', [$mensualiteEleve->id]) }}" class='btn btn-ghost-info'><i class="fa fa-edit"></i></a>
                        {!! Form::button('<i class="fa fa-trash"></i>', ['type' => 'submit', 'class' => 'btn btn-ghost-danger', 'onclick' => "return confirm('Are you sure?')"]) !!}
                    </div>
                    {!! Form::close() !!}
                </td>
            </tr>
        @endforeach
        </tbody>
    </table>
</div>