routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\UserController;
use App\Http\Controllers\EleveController;
use App\Http\Controllers\PaydunyaCarfeisController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
});
Auth::routes(['verify' => true]);
Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Route::post('/connexion', [App\Http\Controllers\UserController::class, 'loginAdmin'])->name('user.connexion');
Route::resource('/user', UserController::class);


Route::resource('typeProfessions', App\Http\Controllers\TypeProfessionController::class);


Route::resource('lienParents', App\Http\Controllers\LienParentController::class);


Route::resource('typeEnseignants', App\Http\Controllers\TypeEnseignantController::class);


Route::resource('type_paiements', App\Http\Controllers\TypePaiementController::class);
Route::post('/add/enseignant/class/{id}',[App\Http\Controllers\EnseignantController::class,'AddEnseignantOnly']);
Route::post('update/{id}',[App\Http\Controllers\UserController::class,'UpdateStatusUser']);
Route::resource('categoryDepenses', App\Http\Controllers\CategoryDepenseController::class);
Route::resource('niveaux', App\Http\Controllers\NiveauController::class);
Route::resource('sousNiveaus', App\Http\Controllers\SousNiveauController::class);
Route::get('status/{id}',[App\Http\Controllers\UserController::class,'getmodalstatus']);
Route::resource('eleves', App\Http\Controllers\EleveController::class);
Route::resource('infoParents', App\Http\Controllers\InfoParentController::class);
Route::resource('alphabetisations', App\Http\Controllers\AlphabetisationController::class);
Route::resource('enseignants', App\Http\Controllers\EnseignantController::class);
Route::get('eleve_classe/{id}',[App\Http\Controllers\EleveController::class,'getEleveAddClass'])->name('getclasse.classe');
Route::get('getclasse/{id}',[App\Http\Controllers\EleveController::class,'getClasseByNiveaau']);
Route::get('add_classe/{id}',[App\Http\Controllers\EleveController::class,'getClasseByNiveaaAdd']);
Route::post('add_eleveclass/{id}',[App\Http\Controllers\EleveController::class,'PostClasseEleve'])->name('eleve.classe');
Route::post('add_eleveclass_withprof/{id}',[App\Http\Controllers\EleveController::class,'PostClasseEleveWithProf']);
Route::resource('eleveClasses', App\Http\Controllers\EleveClasseController::class);
Route::get('getclasseteacher/{id}',[App\Http\Controllers\EnseignantController::class,'getNiveauEnseignantByTypeEnseignant']);
Route::get('getclasseteacher_eleve/{id}',[App\Http\Controllers\EnseignantController::class,'getNiveauEnseignantByClasseEleve']);
Route::get('Addclasseteacher/{id}',[App\Http\Controllers\EnseignantController::class,'AddClassToEnseignant']);
Route::get('edit/enseig/{id}',[App\Http\Controllers\EnseignantController::class,'editClassePro']);
Route::get('edit/enseignant_add_class/{id}',[App\Http\Controllers\EnseignantController::class,'editClasseProfesseurClasse']);
Route::get('getniveau/enseignant/{id}',[App\Http\Controllers\EnseignantController::class,'EditClasseProfesseur']);
Route::get('enseignant_prof_classe/{id}',[App\Http\Controllers\EnseignantController::class,'EditClasseProf']);
Route::post('/update/enseignant/class/{id}',[App\Http\Controllers\EnseignantController::class,'updateClasseEnseignant']);
Route::resource('enseignantClasses', App\Http\Controllers\EnseignantClasseController::class);
Route::delete('/delete/enseignant/class/{id}',[App\Http\Controllers\EnseignantController::class,'deleteSousniveau'])->name('delete.classe');
Route::get('get_eleve_by_class',[App\Http\Controllers\EnseignantController::class,'getClassByEleve'])->name('get_eleve_by_class.classe');
Route::get('getniveau_class/{id}',[App\Http\Controllers\EnseignantController::class,'getClasseByEleve']);
Route::get('get_class_enseig/{id}',[App\Http\Controllers\EnseignantController::class,'getClasseByNiveauEleve']);
Route::get('get_class_all_eleve/{id}',[App\Http\Controllers\EnseignantController::class,'getEleveByClasse']);
Route::get('get_details_eleve/{id}',[App\Http\Controllers\EnseignantController::class,'showdetailseleve'])->name('details_eleve.classe');
Route::get('editclass_elev/{id}',[App\Http\Controllers\EnseignantController::class,'changeEleveClasse'])->name('edit_class.eleve');
Route::get('edit/classe_el/{id}',[App\Http\Controllers\EnseignantController::class,'EditClasseEl']);
Route::get('choice_classe/{id}',[App\Http\Controllers\EnseignantController::class,'getNiveaEleveAdd']);
Route::post('/update/student/class/{id}',[App\Http\Controllers\EnseignantController::class,'updateClasseStudent']);
Route::resource('anneeScolaires', App\Http\Controllers\AnneeScolaireController::class);
Route::get('get_enseignant_on_class', [App\Http\Controllers\EnseignantController::class,'getClasseByTeacher'])->name('get_enseignant_class.eleve');
Route::get('get_enseignantafter_class/{id}', [App\Http\Controllers\EnseignantController::class,'getEnseignantByTypeEnseignement']);
Route::get('get_classe_enseignantafter_class/{id}', [App\Http\Controllers\EnseignantController::class,'getEnseignantByClasseEnseign']);
Route::get('get_classe_eneseignant_eleve/{id}', [App\Http\Controllers\EnseignantController::class,'getEleveByClasseAndEnseignant']);
Route::get('carte_student/{slug}',[App\Http\Controllers\EleveController::class,'getStudentCard'])->name('carte.eleve');
Route::get('carte_all_years/{id}',[App\Http\Controllers\EleveController::class,'getCarteStudentPrinting'])->name('carte.year');

Route::get('get_eleve_to_paiement/{slug}',[App\Http\Controllers\EleveController::class,'getEleveToAddInscription']);
Route::get('get_eleve_on_paiment_by_year',[App\Http\Controllers\EleveController::class,'getPaiementEleveByYear'])->name('paiment.eleve');
Route::post('eleve/new_classes',[App\Http\Controllers\EleveController::class,'getEleveWithNumero'])->name('elevegetting.classe');
Route::post('add_eleve_classe_continuons/{id}',[App\Http\Controllers\EleveController::class,'AddClasseEleveContinuons']);
Route::post('add_eleveclass_with_prof_arab/{id}',[App\Http\Controllers\EleveController::class,'AddClasseEleveContinuonsArabe']);
Route::get('eleve/inscription_new',[App\Http\Controllers\EleveController::class,'getFormtoInscrire'])->name('eleve.new_inscription');
Route::get('eleve/reinscription_new',[App\Http\Controllers\EleveController::class,'getFormtoReInscrire'])->name('eleve.new_reinscription');
Route::resource('inscriptionEleves', App\Http\Controllers\InscriptionEleveController::class);
Route::resource('inscriptionEleves', App\Http\Controllers\InscriptionEleveController::class);
Route::resource('regimes', App\Http\Controllers\RegimeController::class);
Route::resource('fraisInscriptions', App\Http\Controllers\FraisInscriptionController::class);
Route::resource('paiementEleves', App\Http\Controllers\PaiementEleveController::class);
Route::get('get_elevt_to_paie_by_momth/{id}',[App\Http\Controllers\EleveController::class,'getEleveToAddPaiement']);
Route::post('get_elev_paiement',[App\Http\Controllers\EleveController::class,'SearchingElevePaiement'])->name('get_eleve_to_paiement.annee_scolaire');
Route::get('recu/paiement/{slug}',[App\Http\Controllers\PaiementEleveController::class,'getPrinRecu'])->name('get_recu.annee_scolaire');
Route::get('recu/paiement_mensual/{slug}',[App\Http\Controllers\PaiementEleveController::class,'getPaiementMonthRecu'])->name('get_recu_mensual.annee_scolaire');
Route::post('change_status_confime/{id}',[App\Http\Controllers\EleveController::class,'ChangeStatusPaiement']);
Route::resource('enseignantAnnees', App\Http\Controllers\EnseignantAnneeController::class);
Route::post('paiement_mensual/{id}',[App\Http\Controllers\EleveController::class,'PaiementMonthPosted'])->name('paiement.mensual');
Route::resource('mensualiteEleves', App\Http\Controllers\MensualiteEleveController::class);
Route::get('infos_after_paiement/{slug}',[App\Http\Controllers\EleveController::class,'getInfoPaiementMonth'])->name('infor_paiement.mensual');
Route::post('eleve/getting_years',[App\Http\Controllers\EleveController::class,'getEleveNumeroPost'])->name('getting_eleves.classe');
Route::get('/depense_by_category/{slug}',[App\Http\Controllers\DepenseCategorieController::class,'getDeCategory'])->name('depense.category_depense');
Route::get('paiment_enseignant/{slug}',[App\Http\Controllers\MensuualiteEnseignantController::class,'getInfoPaiementEnseignant'])->name('enseignant.paiement');
Route::get('recu_paiment_enseignant/{slug}',[App\Http\Controllers\MensuualiteEnseignantController::class,'getRecuPaiement'])->name('enseignant.recu_paiement');
Route::resource('depenseCategories', App\Http\Controllers\DepenseCategorieController::class);
Route::get('edit_profil/{slug}',[App\Http\Controllers\UserController::class,'ChangeInfoProfile'])->name('edit.profil');
Route::post('edit_profil_user',[App\Http\Controllers\UserController::class,'UpdateProfileAdmin'])->name('edit.profil_user');
Route::post('edit_password_user',[App\Http\Controllers\UserController::class,'ChangePassword'])->name('password.profil_user');
Route::post('changing_password_user/{id}',[App\Http\Controllers\UserController::class,'ChangePasswordUser'])->name('password.changing');
Route::get('get-list-paiement-status',[App\Http\Controllers\PaiementEleveController::class,'getListePaiementStudent'])->name('get_list_status.annuelle');
Route::post('get_list_par_moi',[App\Http\Controllers\PaiementEleveController::class,'getStudentPaiementDayByyear'])->name('get_list_par_moi.annuelle');

app/Models/Enseignant.php
<?php

namespace App\Models;

use Eloquent as Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Cviebrock\EloquentSluggable\Sluggable; 

/**
 * Class Enseignant
 * @package App\Models
 * @version September 21, 2021, 11:10 am UTC
 *
 * @property string $first_name
 * @property string $last_name
 * @property string $phone
 * @property string $adresse
 * @property string $niveau_etude
 * @property string $date_recrutement
 * @property integer $type_enseignant_id
 */
class Enseignant extends Model
{
    use SoftDeletes;
    use Sluggable;

    use HasFactory;

    public $table = 'enseignants';
    

    protected $dates = ['deleted_at'];



    public $fillable = [
        'first_name',
        'last_name',
        'phone',
        'adresse',
        'niveau_etude',
        'date_recrutement',
        'type_enseignant_id',
        'annee_scolaire_id',
        'numero',
        'slug'
    ];

    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [
        'first_name' => 'string',
        'last_name' => 'string',
        'phone' => 'string',
        'adresse' => 'string',
        'niveau_etude' => 'string',
        'date_recrutement' => 'date',
        'type_enseignant_id' => 'integer',
        'annee_scolaire_id'
    ];

    /**
     * Validation rules
     *
     * @var array
     */
    public static $rules = [
        'first_name' => 'required',
        'last_name' => 'required'
    ];

    /**
     * Get the candidat that owns the CandidatureOffre
     *
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function type_enseignant()
    {
        return $this->belongsTo(TypeEnseignant::class, 'type_enseignant_id');
    }


          /**
     * Return the sluggable configuration array for this model.
     *
     * @return array
     */
    public function sluggable(): array
    {
        return [
            'slug' => [
                'source' => ['first_name','last_name'],
            ]
        ];
    } 

      /**
     * Get all of the Alphabetisation for the Niveau
     *
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function mensualite_enseignant()
    {
        return $this->hasMany(MensuualiteEnseignat::class, 'enseignant_id');
    }

        /**
     * Get all of the Alphabetisation for the Niveau
     *
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function enseignant_annee()
    {
        return $this->hasMany(EnseignantAnnee::class, 'enseignant_id');
    }
}

resources/views/enseignants/add_class_prof.blade.php
<strong><label for="recipient-name" class="col-form-label" >Enseignant:</label></strong>
    <select name="enseignant"  class="form-control" onchange="changeFunctionAddStudentProf(this)">
        <option value="">choisir le professeur</option>
        @foreach($niveau_eleve as $niv)
        <option value="{{$niv->id}}">{{$niv->name}}</option>
        @endforeach
<select> 

resources/views/enseignants/add_niveau.blade.php
 @if($type_enseignant->name == "Coran")
<strong><label for="recipient-name" class="col-form-label">Niveau:</label></strong>
    <select name="niveau_id"  class="form-control"  onchange="changeFunctionAddClassePro(this)">
        <option value="">choisir le Niveau</option>
        @foreach($niveau_eleve as $niv)
        <option value="{{$niv->id}}">{{$niv->name}}</option>
        @endforeach
    <select> 
@else  
<strong><label for="recipient-name" class="col-form-label">Niveau:</label></strong>
    <select name="niveau_id"  class="form-control"  onchange="changeFunctionAddClassePro(this)">
    <option value="">choisir le Niveau</option>
    @foreach($niveau_eleve as $niv)
    <option value="{{$niv->id}}" >{{$niv->name}}</option>
    @endforeach
<select> 
 @endif

resources/views/enseignants/addclasse_enseignant.blade.php
@if($niveau_eleve->type_enseignant_id  == "2")
<strong><label for="recipient-name" class="col-form-label">Classe:</label></strong>
    <select name="sous_niveau_id"  class="form-control" >
    <option value="">choisir la classe</option>
    @foreach($class_eleve as $niv)
    <option value="{{$niv->id}}">{{$niv->name}}</option>
    @endforeach
<select>
<input type="hidden" id="niveau" value="{{$niveau_eleve->id}}">
@else
<strong><label for="recipient-name" class="col-form-label">Classe:</label></strong>
    <select name="sous_niveau_id"  class="form-control" onchange="changeFunctionChoiceClass(this)" >
    <option value="">choisir la classe</option>
    @foreach($class_eleve as $niv)
    <option value="{{$niv->id}}">{{$niv->name}}</option>
    @endforeach
<select>
<input type="hidden" id="niveau" value="{{$niveau_eleve->id}}">
@endif

resources/views/enseignants/addniveauclass.blade.php
 <!-- @if($type_enseignant->name == "Arabe")
<strong><label for="recipient-name" class="col-form-label" onchange="changeFunctionshow(this)">Enseignant:</label></strong>
    <select name="enseignant"  class="form-control">
        <option value="">choisir le professeur</option>
        @foreach($niveau_eleve as $niv)
        <option value="{{$niv->id}}">{{$niv->first_name}}</option>
        @endforeach
    <select> 
@else 
<strong><label for="recipient-name" class="col-form-label">Niveau:</label></strong>
    <select name="niveau_id"  class="form-control"  onchange="changeFunctionAddClassePro(this)">
    <option value="">choisir le Niveau</option>
    @foreach($niveau_eleve as $niv)
    <option value="{{$niv->id}}" >{{$niv->name}}</option>
    @endforeach
<select> 
 @endif -->

 <strong><label for="recipient-name" class="col-form-label">Niveau:</label></strong>
    <select name="niveau_id"  class="form-control "  onchange="changeFunctionChoiceClass(this)">
    <option value="">choisir le Niveau</option>
    @foreach($niveau_eleve as $niv)
    <option value="{{$niv->id}}">{{$niv->name}}</option>
    @endforeach
<select> 

resources/views/enseignants/datatables_actions.blade.php
{!! Form::open(['route' => ['enseignants.destroy', $id], 'method' => 'delete']) !!}
<div class='btn-group'>
    <a href="{{ route('enseignants.show', $id) }}" class='btn btn-ghost-success'>
       <i class="fa fa-eye"></i>
    </a>
    <a href="{{ route('enseignants.edit', $id) }}" class='btn btn-ghost-info'>
       <i class="fa fa-edit"></i>
    </a>
    {!! Form::button('<i class="fa fa-trash"></i>', [
        'type' => 'submit',
        'class' => 'btn btn-ghost-danger',
        'onclick' => "return confirm('Are you sure?')"
    ]) !!}
</div>
{!! Form::close() !!}

resources/views/enseignants/edit_status.blade.php
<div class="modal-header">
        <h5 class="modal-title" id="exampleModalLongTitle">Ajout Classe pour {{$enseignant->first_name}}  {{$enseignant->last_name}}</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
</div>
  <div class="modal-body">
    <form  method="POST" >
        @csrf
        <div class="row">
          <div class="form-group col-sm-6">
                <strong><label for="recipient-name" class="col-form-label">Année Scolaire:</label></strong>
                <select name="annee_scolaire_id" id="annee_scolaire_id" class="form-control"  required>
                    <option value="">choisir Année Scolaire</option>
                    <option value="{{$annee_scolaire->id}}">{{$annee_scolaire->name}}</option>
                <select> 
            </div>
            <div class="form-group col-sm-6">
                <strong><label for="recipient-name" class="col-form-label">Type Enseignement:</label></strong>
                <select name="type_enseignant_id" id="type_enseignant_id" class="form-control"  onchange="changeFunctionAjouterClasse(this)" required>
                    <option value="">choisir le type enseignement</option>
                    @foreach($type_enseig as $prof)
                    <option value="{{$prof->id}}">{{$prof->name}}</option>
                    @endforeach
                <select> 
            </div> 
            <input type="hidden" id="enseignant_id" value="{{$enseignant->id}}">
 
            <div class="form-group col-sm-6" >
            <div id="classe_text"></div>
            <div class="niveau_id" ></div>
            </div>
            <div class="form-group col-sm-6" id="close_div">
                <div id="professeur_class" >
                <div id="type_classe_prof" ></div>
                </div>
                <div id="teacher_class_normal" ></div>
            </div>
        </div>
        </div>
        <div class="modal-footer">
            <div id="open_div" style="display:none">
              <button type="button" class="btn btn-secondary" data-dismiss="modal">Fermer</button>
              <button  type="submit" id="update_enseignant" class="btn btn-primary">Ajouter</button>
              </div>
              <div id="clo_div" style="display:none">
              <button type="button" class="btn btn-secondary" data-dismiss="modal">Fermer</button>
              <button  type="submit" id="enseignant_only" class="btn btn-primary">Ajouter</button>
              </div>
    </form>
  </div>

resources/views/enseignants/edit_status_classe.blade.php
<div class="modal-header">
        <h5 class="modal-title" id="exampleModalLongTitle">Ajout Classe pour {{$enseignant->first_name}}  {{$enseignant->last_name}}</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
</div>
  <div class="modal-body">
    <form  method="POST" >
        @csrf
        <div class="row">
            <div class="form-group col-sm-6">
                <strong><label for="recipient-name" class="col-form-label">Année Scolaire:</label></strong>
                <select name="annee_scolaire_id" id="annee_scolaire_id" class="form-control"  required>
                    <option value="">choisir Année Scolaire</option>
                    <option value="{{$annee_scolaire->id}}">{{$annee_scolaire->name}}</option>
                <select> 
            </div> 
            <div class="form-group col-sm-6">
                <strong><label for="recipient-name" class="col-form-label">Type Enseignement:</label></strong>
                <select name="type_enseignant_id" id="type_enseignant_id" class="form-control"  onchange="changeFunctionAjouterClasse(this)" required>
                    <option value="">choisir le type enseignement</option>
                    @foreach($type_enseig as $prof)
                    <option value="{{$prof->id}}">{{$prof->name}}</option>
                    @endforeach
                <select> 
            </div> 
            <input type="hidden" id="enseignant_id" value="{{$enseignant->id}}">
 
            <div class="form-group col-sm-6" >
            <div id="classe_text"></div>
            <div class="niveau_id" ></div>
            </div>
            <div class="form-group col-sm-6" id="close_div">
                <div id="professeur_class" >
                <div id="type_classe_prof" ></div>
                </div>
                <div id="teacher_class_normal" ></div>
            </div>
        </div>
        </div>
        <div class="modal-footer">
            <div id="open_div" style="display:none">
              <button type="button" class="btn btn-secondary" data-dismiss="modal">Fermer</button>
              <button  type="submit" id="update_enseignant" class="btn btn-primary">Ajouter</button>
              </div>
              <div id="clo_div" style="display:none">
              <button type="button" class="btn btn-secondary" data-dismiss="modal">Fermer</button>
              <button  type="submit" id="enseignant_only" class="btn btn-primary">Ajouter</button>
              </div>
    </form>
  </div>

resources/views/enseignants/fields.blade.php
<!-- First Name Field -->
<div class="row">
<div class="form-group col-sm-6">
        <strong><label for="recipient-name" class="col-form-label">Année Scolaire:</label></strong>
        <select name="annee_scolaire_id" id="annee_scolaire_id" class="form-control" required>
            <option value="">choisir Année scolaire</option>
            <option value="{{$annee_scolaire->id}}">{{$annee_scolaire->name}}</option>
        <select> 
    </div>  
<div class="form-group col-sm-6">
    {!! Form::label('first_name', 'Prénom:') !!}
    {!! Form::text('first_name', null, ['class' => 'form-control','required' => true]) !!}
</div>

<!-- Last Name Field -->
<div class="form-group col-sm-6">
    {!! Form::label('last_name', 'Nom:') !!}
    {!! Form::text('last_name', null, ['class' => 'form-control','required' => true]) !!}
</div>

<!-- Phone Field -->
<div class="form-group col-sm-6">
    {!! Form::label('phone', 'Téléphone:') !!}
    {!! Form::text('phone', null, ['class' => 'form-control']) !!}
</div>

<!-- Adresse Field -->
<div class="form-group col-sm-6">
    {!! Form::label('adresse', 'Adresse:') !!}
    {!! Form::text('adresse', null, ['class' => 'form-control']) !!}
</div>

<!-- Niveau Etude Field -->
<div class="form-group col-sm-6">
    {!! Form::label('niveau_etude', 'Niveau Etude:') !!}
    {!! Form::text('niveau_etude', null, ['class' => 'form-control']) !!}
</div>

<!-- Date Recrutement Field -->
<div class="form-group col-sm-6">
    {!! Form::label('date_recrutement', 'Date de Recrutement:') !!}
    {!! Form::date('date_recrutement', null, ['class' => 'form-control','id'=>'date_recrutement','required' => true]) !!}
</div>

{{-- 
@if(empty($enseignant))
<div class="form-group col-sm-6">
    {!! Form::label('type_enseignant_id', 'Type Enseigement:') !!}
    <select name="type_enseignant_id" id="status" class="form-control"   onchange="changeFunctionEnseignant(this)" required>
        <option value="">--Choisir enseignement --</option>
        @foreach($type_enseig as $type)
        @if(!empty($enseignant->type_enseignant))
        @if($type->id === $enseignant->type_enseignant->id)
        <option value="{{$enseignant->type_enseignant->id}}" selected>{{$enseignant->type_enseignant->name}}</option>
        @endif
        @else
        <option value="{{$type->id}}" >{{$type->name}}</option>
        @endif
        @endforeach
    </select>
</div>
    <div class="form-group col-sm-6" id="hid_div"  >
        <div id="teacher_text"></div>
        <div id="teachniv_id"></div>
    </div>
    <div class="form-group col-sm-6" id="hide_div" >
        <div id="teacher_class"></div>
        <div id="teacher_class_id"></div>
    </div>
    @endif
</div>
--}}
<!-- Submit Field -->
<div class="form-group col-sm-12">
    {!! Form::submit('Ajouter', ['class' => 'btn btn-primary']) !!}
    <a href="{{ route('enseignants.index') }}" class="btn btn-secondary">Annuler</a>
</div>

resources/views/enseignants/get_enseignant.blade.php
<strong><label for="recipient-name" class="col-form-label">Liste des Enseignants:</label></strong>
    <select name="type_enseignant_id" id="type_enseignant_id" class="form-control"  onchange="getClasseByEnseignant(this)" required>
    <option value="">choisir l'enseignement</option>
    @foreach($niveau_enseignant as $prof)
    <option value="{{$prof->enseignant_id}}">{{$prof->name}} </option>
    @endforeach
<select> 

resources/views/enseignants/index.blade.php
@extends('layouts.app')

@section('content')
    <ol class="breadcrumb">
        <li class="breadcrumb-item">Enseignants</li>
    </ol>
    <div class="container-fluid">
        <div class="animated fadeIn">
             @include('flash::message')
             <div class="row">
                 <div class="col-lg-12">
                     <div class="card">
                         <div class="card-header">
                             <i class="fa fa-align-justify"></i>
                             Enseignants
                             <a class="pull-right" href="{{ route('enseignants.create') }}"><i class="fa fa-plus-square fa-lg"></i></a>
                         </div>
                         <div class="card-body">
                             @include('enseignants.table')
                              <div class="pull-right mr-3">
                                     
                              </div>
                         </div>
                     </div>
                  </div>
             </div>
         </div>
    </div>
@endsection

resources/views/enseignants/show.blade.php
@extends('layouts.app')

@section('content')
     <ol class="breadcrumb">
            <li class="breadcrumb-item">
                <a href="{{ route('enseignants.index') }}">Enseignant</a>
            </li>
            <li class="breadcrumb-item active">Detail</li>
     </ol>
     <div class="container-fluid">
          <div class="animated fadeIn">
                 @include('coreui-templates::common.errors')
                 <div class="row">
                     <div class="col-lg-12">
                         <div class="card">
                             <div class="card-header">
                                 <strong>Details</strong>
                                  <a href="{{ route('enseignants.index') }}" class="btn btn-light">Back</a>
                             </div>
                             <div class="card-body">
                                 @include('enseignants.show_fields')
                             </div>
                         </div>
                     </div>
                 </div>
          </div>
    </div>
@endsection

resources/views/enseignants/table.blade.php
@section('css')
    @include('layouts.datatables_css')
@endsection

{!! $dataTable->table(['width' => '100%', 'class' => 'table table-striped table-bordered']) !!}

@push('scripts')
    @include('layouts.datatables_js')
    {!! $dataTable->scripts() !!}
@endpush