routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\UserController;
use App\Http\Controllers\EleveController;
use App\Http\Controllers\PaydunyaCarfeisController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
});
Auth::routes(['verify' => true]);
Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Route::post('/connexion', [App\Http\Controllers\UserController::class, 'loginAdmin'])->name('user.connexion');
Route::resource('/user', UserController::class);


Route::resource('typeProfessions', App\Http\Controllers\TypeProfessionController::class);


Route::resource('lienParents', App\Http\Controllers\LienParentController::class);


Route::resource('typeEnseignants', App\Http\Controllers\TypeEnseignantController::class);


Route::resource('type_paiements', App\Http\Controllers\TypePaiementController::class);
Route::post('/add/enseignant/class/{id}',[App\Http\Controllers\EnseignantController::class,'AddEnseignantOnly']);
Route::post('update/{id}',[App\Http\Controllers\UserController::class,'UpdateStatusUser']);
Route::resource('categoryDepenses', App\Http\Controllers\CategoryDepenseController::class);
Route::resource('niveaux', App\Http\Controllers\NiveauController::class);
Route::resource('sousNiveaus', App\Http\Controllers\SousNiveauController::class);
Route::get('status/{id}',[App\Http\Controllers\UserController::class,'getmodalstatus']);
Route::resource('eleves', App\Http\Controllers\EleveController::class);
Route::resource('infoParents', App\Http\Controllers\InfoParentController::class);
Route::resource('alphabetisations', App\Http\Controllers\AlphabetisationController::class);
Route::resource('enseignants', App\Http\Controllers\EnseignantController::class);
Route::get('eleve_classe/{id}',[App\Http\Controllers\EleveController::class,'getEleveAddClass'])->name('getclasse.classe');
Route::get('getclasse/{id}',[App\Http\Controllers\EleveController::class,'getClasseByNiveaau']);
Route::get('add_classe/{id}',[App\Http\Controllers\EleveController::class,'getClasseByNiveaaAdd']);
Route::post('add_eleveclass/{id}',[App\Http\Controllers\EleveController::class,'PostClasseEleve'])->name('eleve.classe');
Route::post('add_eleveclass_withprof/{id}',[App\Http\Controllers\EleveController::class,'PostClasseEleveWithProf']);
Route::resource('eleveClasses', App\Http\Controllers\EleveClasseController::class);
Route::get('getclasseteacher/{id}',[App\Http\Controllers\EnseignantController::class,'getNiveauEnseignantByTypeEnseignant']);
Route::get('getclasseteacher_eleve/{id}',[App\Http\Controllers\EnseignantController::class,'getNiveauEnseignantByClasseEleve']);
Route::get('Addclasseteacher/{id}',[App\Http\Controllers\EnseignantController::class,'AddClassToEnseignant']);
Route::get('edit/enseig/{id}',[App\Http\Controllers\EnseignantController::class,'editClassePro']);
Route::get('edit/enseignant_add_class/{id}',[App\Http\Controllers\EnseignantController::class,'editClasseProfesseurClasse']);
Route::get('getniveau/enseignant/{id}',[App\Http\Controllers\EnseignantController::class,'EditClasseProfesseur']);
Route::get('enseignant_prof_classe/{id}',[App\Http\Controllers\EnseignantController::class,'EditClasseProf']);
Route::post('/update/enseignant/class/{id}',[App\Http\Controllers\EnseignantController::class,'updateClasseEnseignant']);
Route::resource('enseignantClasses', App\Http\Controllers\EnseignantClasseController::class);
Route::delete('/delete/enseignant/class/{id}',[App\Http\Controllers\EnseignantController::class,'deleteSousniveau'])->name('delete.classe');
Route::get('get_eleve_by_class',[App\Http\Controllers\EnseignantController::class,'getClassByEleve'])->name('get_eleve_by_class.classe');
Route::get('getniveau_class/{id}',[App\Http\Controllers\EnseignantController::class,'getClasseByEleve']);
Route::get('get_class_enseig/{id}',[App\Http\Controllers\EnseignantController::class,'getClasseByNiveauEleve']);
Route::get('get_class_all_eleve/{id}',[App\Http\Controllers\EnseignantController::class,'getEleveByClasse']);
Route::get('get_details_eleve/{id}',[App\Http\Controllers\EnseignantController::class,'showdetailseleve'])->name('details_eleve.classe');
Route::get('editclass_elev/{id}',[App\Http\Controllers\EnseignantController::class,'changeEleveClasse'])->name('edit_class.eleve');
Route::get('edit/classe_el/{id}',[App\Http\Controllers\EnseignantController::class,'EditClasseEl']);
Route::get('choice_classe/{id}',[App\Http\Controllers\EnseignantController::class,'getNiveaEleveAdd']);
Route::post('/update/student/class/{id}',[App\Http\Controllers\EnseignantController::class,'updateClasseStudent']);
Route::resource('anneeScolaires', App\Http\Controllers\AnneeScolaireController::class);
Route::get('get_enseignant_on_class', [App\Http\Controllers\EnseignantController::class,'getClasseByTeacher'])->name('get_enseignant_class.eleve');
Route::get('get_enseignantafter_class/{id}', [App\Http\Controllers\EnseignantController::class,'getEnseignantByTypeEnseignement']);
Route::get('get_classe_enseignantafter_class/{id}', [App\Http\Controllers\EnseignantController::class,'getEnseignantByClasseEnseign']);
Route::get('get_classe_eneseignant_eleve/{id}', [App\Http\Controllers\EnseignantController::class,'getEleveByClasseAndEnseignant']);
Route::get('carte_student/{slug}',[App\Http\Controllers\EleveController::class,'getStudentCard'])->name('carte.eleve');
Route::get('carte_all_years/{id}',[App\Http\Controllers\EleveController::class,'getCarteStudentPrinting'])->name('carte.year');

Route::get('get_eleve_to_paiement/{slug}',[App\Http\Controllers\EleveController::class,'getEleveToAddInscription']);
Route::get('get_eleve_on_paiment_by_year',[App\Http\Controllers\EleveController::class,'getPaiementEleveByYear'])->name('paiment.eleve');
Route::post('eleve/new_classes',[App\Http\Controllers\EleveController::class,'getEleveWithNumero'])->name('elevegetting.classe');
Route::post('add_eleve_classe_continuons/{id}',[App\Http\Controllers\EleveController::class,'AddClasseEleveContinuons']);
Route::post('add_eleveclass_with_prof_arab/{id}',[App\Http\Controllers\EleveController::class,'AddClasseEleveContinuonsArabe']);
Route::get('eleve/inscription_new',[App\Http\Controllers\EleveController::class,'getFormtoInscrire'])->name('eleve.new_inscription');
Route::get('eleve/reinscription_new',[App\Http\Controllers\EleveController::class,'getFormtoReInscrire'])->name('eleve.new_reinscription');
Route::resource('inscriptionEleves', App\Http\Controllers\InscriptionEleveController::class);
Route::resource('inscriptionEleves', App\Http\Controllers\InscriptionEleveController::class);
Route::resource('regimes', App\Http\Controllers\RegimeController::class);
Route::resource('fraisInscriptions', App\Http\Controllers\FraisInscriptionController::class);
Route::resource('paiementEleves', App\Http\Controllers\PaiementEleveController::class);
Route::get('get_elevt_to_paie_by_momth/{id}',[App\Http\Controllers\EleveController::class,'getEleveToAddPaiement']);
Route::post('get_elev_paiement',[App\Http\Controllers\EleveController::class,'SearchingElevePaiement'])->name('get_eleve_to_paiement.annee_scolaire');
Route::get('recu/paiement/{slug}',[App\Http\Controllers\PaiementEleveController::class,'getPrinRecu'])->name('get_recu.annee_scolaire');
Route::get('recu/paiement_mensual/{slug}',[App\Http\Controllers\PaiementEleveController::class,'getPaiementMonthRecu'])->name('get_recu_mensual.annee_scolaire');
Route::post('change_status_confime/{id}',[App\Http\Controllers\EleveController::class,'ChangeStatusPaiement']);
Route::resource('enseignantAnnees', App\Http\Controllers\EnseignantAnneeController::class);
Route::post('paiement_mensual/{id}',[App\Http\Controllers\EleveController::class,'PaiementMonthPosted'])->name('paiement.mensual');
Route::resource('mensualiteEleves', App\Http\Controllers\MensualiteEleveController::class);
Route::get('infos_after_paiement/{slug}',[App\Http\Controllers\EleveController::class,'getInfoPaiementMonth'])->name('infor_paiement.mensual');
Route::post('eleve/getting_years',[App\Http\Controllers\EleveController::class,'getEleveNumeroPost'])->name('getting_eleves.classe');
Route::get('/depense_by_category/{slug}',[App\Http\Controllers\DepenseCategorieController::class,'getDeCategory'])->name('depense.category_depense');
Route::get('paiment_enseignant/{slug}',[App\Http\Controllers\MensuualiteEnseignantController::class,'getInfoPaiementEnseignant'])->name('enseignant.paiement');
Route::get('recu_paiment_enseignant/{slug}',[App\Http\Controllers\MensuualiteEnseignantController::class,'getRecuPaiement'])->name('enseignant.recu_paiement');
Route::resource('depenseCategories', App\Http\Controllers\DepenseCategorieController::class);
Route::get('edit_profil/{slug}',[App\Http\Controllers\UserController::class,'ChangeInfoProfile'])->name('edit.profil');
Route::post('edit_profil_user',[App\Http\Controllers\UserController::class,'UpdateProfileAdmin'])->name('edit.profil_user');
Route::post('edit_password_user',[App\Http\Controllers\UserController::class,'ChangePassword'])->name('password.profil_user');
Route::post('changing_password_user/{id}',[App\Http\Controllers\UserController::class,'ChangePasswordUser'])->name('password.changing');
Route::get('get-list-paiement-status',[App\Http\Controllers\PaiementEleveController::class,'getListePaiementStudent'])->name('get_list_status.annuelle');
Route::post('get_list_par_moi',[App\Http\Controllers\PaiementEleveController::class,'getStudentPaiementDayByyear'])->name('get_list_par_moi.annuelle');

resources/views/niveaux/create.blade.php
@extends('layouts.app')

@section('content')
    <ol class="breadcrumb">
      <li class="breadcrumb-item">
         <a href="{!! route('niveaux.index') !!}">Niveau</a>
      </li>
      <li class="breadcrumb-item active">Create</li>
    </ol>
     <div class="container-fluid">
          <div class="animated fadeIn">
                @include('coreui-templates::common.errors')
                <div class="row">
                    <div class="col-lg-12">
                        <div class="card">
                            <div class="card-header">
                                <i class="fa fa-plus-square-o fa-lg"></i>
                                <strong>Create Niveau</strong>
                            </div>
                            <div class="card-body">
                                {!! Form::open(['route' => 'niveaux.store']) !!}

                                   @include('niveaux.fields')

                                {!! Form::close() !!}
                            </div>
                        </div>
                    </div>
                </div>
           </div>
    </div>
@endsection

resources/views/niveaux/datatables_actions.blade.php
{!! Form::open(['route' => ['niveaux.destroy', $id], 'method' => 'delete']) !!}
<div class='btn-group'>
    <a href="{{ route('niveaux.show', $id) }}" class='btn btn-ghost-success'>
       <i class="fa fa-eye"></i>
    </a>
    <a href="{{ route('niveaux.edit', $id) }}" class='btn btn-ghost-info'>
       <i class="fa fa-edit"></i>
    </a>
    {!! Form::button('<i class="fa fa-trash"></i>', [
        'type' => 'submit',
        'class' => 'btn btn-ghost-danger',
        'onclick' => "return confirm('Are you sure?')"
    ]) !!}
</div>
{!! Form::close() !!}

resources/views/niveaux/edit.blade.php
@extends('layouts.app')

@section('content')
    <ol class="breadcrumb">
          <li class="breadcrumb-item">
             <a href="{!! route('niveaux.index') !!}">Niveau</a>
          </li>
          <li class="breadcrumb-item active">Edit</li>
        </ol>
    <div class="container-fluid">
        <div class="animated fadeIn">
             @include('coreui-templates::common.errors')
             {!! Form::model($niveau, ['route' => ['niveaux.update', $niveau->id], 'method' => 'patch']) !!}
                <div class="row">
                    <div class="col-lg-6">
                        <div class="card">
                          <div class="card-header">
                              <i class="fa fa-edit fa-lg"></i>
                              <strong>Edit Niveau</strong>
                          </div>
                          <div class="card-body">
                              @include('niveaux.fields')

                            </div>
                        </div>
                    </div>
                    <div class="col-sm-6">
                        <div class="card">
                            <div class="card-header">
                                <i class="fa fa-align-justify"></i>
                                SousNiveaus
                                <a class="add_form_field1 pull-right"  name="s_niveau[]" href=""><i class="fa fa-plus-square fa-lg"></i></a>
                            </div>
                            <div class="card-body">
                                 @include('niveaux.s_table')
                                <div class="pull-right mr-3">
                                        
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="form-group col-sm-12">
                    {!! Form::submit('Ajouter', ['class' => 'btn btn-primary']) !!}
                    <a href="{{ route('niveaux.index') }}" class="btn btn-secondary">Annuler</a>
                </div>
                </div>
                {!! Form::close() !!}

        </div>
    </div>
@endsection

resources/views/niveaux/fields.blade.php
@if(!empty($niveau))
<div class="row">
    <div class="form-group col-sm-6">
        <strong>{!! Form::label('type_enseignant_id', 'Type Enseignement:') !!}</strong> 
        <select name="type_enseignant_id" id="status" class="form-control" required>
            <option value="">--Choisir le type enseignement --</option>
            @foreach($type_enseig as $type)
                @if(!empty($niveau->type_enseignant))
                    @if($type->id === $niveau->type_enseignant->id)
                    <option value="{{$type->id}}" selected>{{$type->name}}</option>
                    @endif
                    @if($type->id != $niveau->type_enseignant->id)
                    <option value="{{$type->id}}" >{{$type->name}}</option>
                    @endif
                @else
                <option value="{{$type->id}}" >{{$type->name}}</option>
                @endif
            @endforeach
        </select>
    </div>
    <div class="form-group col-sm-6">
       <strong>{!! Form::label('name', 'Niveaux:') !!}</strong>
        {!! Form::text('name', null, ['class' => 'form-control']) !!}
    </div>
</div>
@else
<section class="tailles p-4">
    <div class="row">
        <div class="form-group col-sm-6">
         <strong> {!! Form::label('type_enseignant_id', 'Type Enseignement:') !!}</strong>  
            <select name="type_enseignant_id" id="type_enseignant_id" class="form-control" required>
                <option value="">--Choisir le type Enseignement --</option>
                @foreach($type_enseig as $type)
                <option value="{{$type->id}}" >{{$type->name}}</option>
                @endforeach
            </select>
        </div>
        <div class="form-group col-sm-6">
           <strong> {!! Form::label('name', 'Niveaux:') !!}</strong>
            {!! Form::text('name', null, ['class' => 'form-control']) !!}
        </div>
    </div>
        <div class="mt-1">
            <div class="col-md-12">
                <h3 class="form-section-title">Associer le niveau avec  des Classe</h3>
            </div>
        </div><!--/.row-->
        <div class="row dynamic_taille_field_container">
            <div class="col-md-2 offset-md-10 niveau_added mt-3 mb-4">
                <button class="add_form_field form-control" name="s_niveau[]" style="background-color:#3e0f05 ;">
                    <span style="font-size:16px; font-weight:bold;">+</span>
                </button>
            </div><!--/.col-md-6 -->
        </div>
        <div class="container top">
            <div class="row taille-container" style="display:flex;">
                <div class="col-md-6 mt-3">
                    <input class="form-control" type="text" placeholder="classe 1" name="s_niveau1" required>
                </div>
            </div>
        </div>
</section>
<!-- Submit Field -->
<div class="form-group col-sm-12">
    {!! Form::submit('Ajouter', ['class' => 'btn btn-primary']) !!}
    <a href="{{ route('niveaux.index') }}" class="btn btn-secondary">Annuler</a>
</div>
@endif

resources/views/niveaux/index.blade.php
@extends('layouts.app')

@section('content')
    <ol class="breadcrumb">
        <li class="breadcrumb-item">Niveaux</li>
    </ol>
    <div class="container-fluid">
        <div class="animated fadeIn">
             @include('flash::message')
             <div class="row">
                 <div class="col-lg-12">
                     <div class="card">
                         <div class="card-header">
                             <i class="fa fa-align-justify"></i>
                             Niveaux
                             <a class="pull-right" href="{{ route('niveaux.create') }}"><i class="fa fa-plus-square fa-lg"></i></a>
                         </div>
                         <div class="card-body">
                             @include('niveaux.table')
                              <div class="pull-right mr-3">
                                     
                              </div>
                         </div>
                     </div>
                  </div>
             </div>
         </div>
    </div>
@endsection

resources/views/niveaux/s_table.blade.php
<div class="table-responsive-sm">
    <table class="table table-striped" id="sousNiveaus-table">
        <thead>
            <tr>
                <th>Name</th>
                <th colspan="3">Action</th>
            </tr>
        </thead>
        <tbody>
        @foreach($s_niveau as $sousNiveau)
            <tr>
                <td>{{ $sousNiveau->name }}</td>
                <td>
                    <div class='btn-group'>
                        <a href="{{ route('sousNiveaus.edit', [$sousNiveau->id]) }}" class='btn btn-ghost-info'><i class="fa fa-edit"></i></a>
                    </div>
                </td>
            </tr>
        @endforeach
        </tbody>
    </table>
    <div class="row taille-container" style="display:flex;">

    </div>
</div>

resources/views/niveaux/show.blade.php
@extends('layouts.app')

@section('content')
     <ol class="breadcrumb">
            <li class="breadcrumb-item">
                <a href="{{ route('niveaux.index') }}">Niveau</a>
            </li>
            <li class="breadcrumb-item active">Detail</li>
     </ol>
     <div class="container-fluid">
          <div class="animated fadeIn">
                 @include('coreui-templates::common.errors')
                 <div class="row">
                     <div class="col-lg-12">
                         <div class="card">
                             <div class="card-header">
                                  <a href="{{ route('niveaux.index') }}" class="btn btn-light">Retour</a>
                             </div>
                             <div class="card-body">
                                 @include('niveaux.show_fields')
                             </div>
                         </div>
                     </div>
                 </div>
          </div>
    </div>
@endsection

resources/views/niveaux/show_fields.blade.php
<!-- Name Field -->
<div class="form-group">
   <strong>{!! Form::label('name', 'Niveau:') !!}</strong> 
    <p>{{ $niveau->name }}</p>
</div>
@if(!($s_niveau->isEmpty()))
<div class="table-responsive-sm">
    <table class="table table-striped" id="sousNiveaus-table">
        <thead>
            <tr>
                <th>Classe associées</th>
                <th colspan="3">Action</th>
            </tr>
        </thead>
        <tbody>
        @foreach($s_niveau as $sousNiveau)
            <tr>
                <td>{{ $sousNiveau->name }}</td>
                <td>
                    {!! Form::open(['route' => ['sousNiveaus.destroy', $sousNiveau->id], 'method' => 'delete']) !!}
                    <div class='btn-group'>
                        <a href="{{ route('sousNiveaus.edit', [$sousNiveau->id]) }}" class='btn btn-ghost-info'><i class="fa fa-edit"></i></a>
                        {!! Form::button('<i class="fa fa-trash"></i>', ['type' => 'submit', 'class' => 'btn btn-ghost-danger', 'onclick' => "return confirm('Are you sure?')"]) !!}
                    </div>
                    {!! Form::close() !!}
                </td>
            </tr>
        @endforeach
        </tbody>
    </table>
</div>
@else
<div class="alert alert-warning" role="alert">
  Aucune classe assosciée
</div>
@endif

resources/views/niveaux/table.blade.php
@section('css')
    @include('layouts.datatables_css')
@endsection

{!! $dataTable->table(['width' => '100%', 'class' => 'table table-striped table-bordered']) !!}

@push('scripts')
    @include('layouts.datatables_js')
    {!! $dataTable->scripts() !!}
@endpush